workflows:
  # TestFlight Distribution (No UDID Required)
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gopayna.app
      vars:
        BUNDLE_ID: "com.gopayna.app"
        # Set these in Codemagic UI as encrypted variables
        # APP_STORE_CONNECT_ISSUER_ID: Your issuer ID
        # APP_STORE_CONNECT_KEY_IDENTIFIER: Your key ID  
        # APP_STORE_CONNECT_PRIVATE_KEY: Your private key
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: release
          include: true
          source: true
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Build IPA for TestFlight
        script: |
          flutter build ipa --release \
            --export-method=app-store \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - valuemaxcodershub@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
  ios-device:
    name: iOS Device Testing Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: development
        bundle_identifier: com.gopayna.app
      vars:
        BUNDLE_ID: "com.gopayna.app"
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Build IPA for device testing
        script: |
          flutter build ipa --release \
            --export-method=development \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - valuemaxcodershub@gmail.com
        notify:
          success: true
          failure: true

  # iOS Development Build (Simulator Only)
  ios-development:
    name: iOS Development Build  
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.gopayna.app.dev"
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Build iOS for development (no signing)
        script: |
          flutter build ios --debug --no-codesign \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/iphoneos/Runner.app
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - valuemaxcodershub@gmail.com
        notify:
          success: true
          failure: true

  # iOS App Store Distribution Build (Requires Code Signing)
  ios-appstore:
    name: iOS App Store Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.gopayna.app"
        # These will be set in Codemagic web interface as encrypted variables
        # APP_STORE_CONNECT_ISSUER_ID: Set in Codemagic UI
        # APP_STORE_CONNECT_KEY_IDENTIFIER: Set in Codemagic UI  
        # APP_STORE_CONNECT_PRIVATE_KEY: Set in Codemagic UI
        # CERTIFICATE_PRIVATE_KEY: Set in Codemagic UI
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: release/*
          include: true
          source: true
    scripts:
      - name: Set up keychain for code signing
        script: |
          keychain initialize
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build IPA for App Store
        script: |
          flutter build ipa --release \
            --export-method=app-store \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - valuemaxcodershub@gmail.com # Replace with your email
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
        
  # iOS Development/Testing Build (Simulator)
  ios-debug:
    name: iOS Debug Build (Simulator)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.gopayna.app"
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
        - pattern: feature/*
          include: true
          source: true
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Run Flutter tests
        script: |
          flutter test
      - name: Build iOS debug for simulator
        script: |
          flutter build ios --debug --simulator
    artifacts:
      - build/ios/iphonesimulator/Runner.app
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - valuemaxcodershub@gmail.com # Replace with your email
        notify:
          success: false
          failure: true